services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-network-homework
    environment:
      - MYSQL_DATABASE=network_homework
      - MYSQL_USER=network_user
      - MYSQL_PASSWORD=wkm20040818@
      - MYSQL_ROOT_PASSWORD=wkm20040818@
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
    image: network-homework-app
    container_name: network-homework-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/network_homework?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=network_user
      - SPRING_DATASOURCE_PASSWORD=wkm20040818@
      - SPRING_MAIL_HOST=smtp.qq.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=937238852@qq.com
      - SPRING_MAIL_PASSWORD=akxpzriwzxifbefd
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=false
      - SPRING_MAIL_DEFAULT_ENCODING=UTF-8
      - SPRING_MAIL_FROM=937238852@qq.com
    ports:
      - "8080:8080"

volumes:
  db-data:
